// Okapi BM25 — hand-rolled port of rank-bm25 0.2.2 BM25Okapi.
//
// Replicates the exact (and slightly nonstandard) semantics of rank-bm25's
// BM25Okapi so the Worker ranks the 23-snippet KB identically to the Python
// lean build. The parity trap is the negative-IDF flooring step. Verified
// against worker/test/fixtures/bm25_parity.json (generated by the real Python
// path in scripts/gen_bm25_fixtures.py). Mirrors:
//   - tokenize: lowercase then /[a-z0-9]+/g (sparse.py:11-15)
//   - doc text: `${title} ${content} ${category}` (sparse.py:23-25)
//   - params: k1=1.5, b=0.75, epsilon=0.25
//   - IDF: ln(N - df + 0.5) - ln(df + 0.5), NO +1
//   - average_idf = sum(all idfs) / vocabSize (includes negatives)
//   - words with idf < 0 floored to epsilon * average_idf
//   - unseen query term contributes 0
//   - per-occurrence accumulation of duplicate query tokens
//   - retrieve(query, k=4): stable sort desc (ties by original index),
//     return first k with score > 0 (sparse.py:28-34)

import type { Snippet } from "./types";

const TOKEN_RE = /[a-z0-9]+/g;

export function tokenize(text: string): string[] {
  return text.toLowerCase().match(TOKEN_RE) ?? [];
}

export class BM25Okapi {
  private readonly k1: number;
  private readonly b: number;
  private readonly epsilon: number;

  private readonly corpusSize: number;
  private readonly avgdl: number;
  /** Per-document term frequencies. */
  private readonly docFreqs: Map<string, number>[];
  /** Per-document length (token count). */
  private readonly docLen: number[];
  /** Word -> idf (after negative-idf flooring). */
  private readonly idf: Map<string, number>;

  constructor(
    corpus: string[][],
    k1 = 1.5,
    b = 0.75,
    epsilon = 0.25,
  ) {
    this.k1 = k1;
    this.b = b;
    this.epsilon = epsilon;

    this.corpusSize = corpus.length;
    this.docFreqs = [];
    this.docLen = [];
    this.idf = new Map();

    // _initialize: doc lengths, per-doc frequencies, document-frequency counts.
    const nd = new Map<string, number>(); // word -> number of docs containing it
    let numDoc = 0;
    for (const document of corpus) {
      this.docLen.push(document.length);
      numDoc += document.length;

      const frequencies = new Map<string, number>();
      for (const word of document) {
        frequencies.set(word, (frequencies.get(word) ?? 0) + 1);
      }
      this.docFreqs.push(frequencies);

      for (const word of frequencies.keys()) {
        nd.set(word, (nd.get(word) ?? 0) + 1);
      }
    }
    this.avgdl = numDoc / this.corpusSize;

    // _calc_idf: ln IDF (no +1), then floor idf < 0 to epsilon * average_idf.
    let idfSum = 0;
    const negativeIdfs: string[] = [];
    for (const [word, freq] of nd) {
      const idf =
        Math.log(this.corpusSize - freq + 0.5) - Math.log(freq + 0.5);
      this.idf.set(word, idf);
      idfSum += idf;
      if (idf < 0) {
        negativeIdfs.push(word);
      }
    }
    const averageIdf = idfSum / this.idf.size; // vocab size (includes negatives)
    const eps = this.epsilon * averageIdf;
    for (const word of negativeIdfs) {
      this.idf.set(word, eps);
    }
  }

  /** BM25 score for every document, in corpus order (mirrors get_scores). */
  getScores(query: string[]): number[] {
    const score = new Array<number>(this.corpusSize).fill(0);
    // Per-occurrence accumulation: iterate each query token (duplicates count).
    for (const q of query) {
      const idf = this.idf.get(q) ?? 0; // unseen term -> 0
      if (idf === 0) {
        continue; // contributes 0 to every doc; (x || 0) parity is preserved
      }
      for (let i = 0; i < this.corpusSize; i++) {
        const qFreq = this.docFreqs[i].get(q) ?? 0;
        const denom =
          qFreq +
          this.k1 * (1 - this.b + (this.b * this.docLen[i]) / this.avgdl);
        score[i] += (idf * (qFreq * (this.k1 + 1))) / denom;
      }
    }
    return score;
  }
}

/** BM25 keyword retriever over the knowledge snippets (sparse.py parity). */
export class BM25Retriever {
  private readonly snippets: Snippet[];
  private readonly bm25: BM25Okapi;

  constructor(snippets: Snippet[]) {
    this.snippets = snippets;
    const corpus = snippets.map((s) =>
      tokenize(`${s.title} ${s.content} ${s.category}`),
    );
    this.bm25 = new BM25Okapi(corpus);
  }

  /** Top-k snippets by BM25 score (positive scores only). */
  retrieve(query: string, k = 4): Snippet[] {
    const scores = this.bm25.getScores(tokenize(query));
    // Stable descending sort: ties keep original (lower) index order, matching
    // Python's sorted(..., reverse=True) on a range of indices (sparse.py:31-33).
    const ranked = scores
      .map((score, index) => ({ score, index }))
      .sort((a, b) => b.score - a.score || a.index - b.index);
    const out: Snippet[] = [];
    for (const { score, index } of ranked) {
      if (out.length >= k) {
        break;
      }
      if (score > 0) {
        out.push(this.snippets[index]);
      }
    }
    return out;
  }

  /** Ranked ids + scores for all positive-scoring docs (fixture/parity use). */
  rankAll(query: string): { ids: string[]; scores: number[] } {
    const scores = this.bm25.getScores(tokenize(query));
    const ranked = scores
      .map((score, index) => ({ score, index }))
      .sort((a, b) => b.score - a.score || a.index - b.index);
    return {
      ids: ranked.map((r) => this.snippets[r.index].id),
      scores: ranked.map((r) => r.score),
    };
  }
}
