// Agent parity + tool-loop behavior tests.
//
// Parity cases come from worker/test/fixtures/agent_parity.json, generated by
// scripts/gen_agent_fixtures.py from the REAL Python agent stack (router.route,
// tools.web_search_tool, agent.py hint, anthropic.py max-iters reply). Loop
// behavior is tested by scripting raw stream events through runAgentStream.

import { describe, expect, it } from "vitest";

import {
  MAX_ITERS_REPLY,
  retrieveKnowledgeTool,
  route,
  routingHint,
  runAgentStream,
  webSearchTool,
  type AgentStreamEvent,
  type ToolSpec,
} from "../src/agent";
import type { SseSink } from "../src/sse";
import type { Snippet } from "../src/types";
import fixture from "./fixtures/agent_parity.json";

// --- fixture parity ----------------------------------------------------------

describe("router parity (router.py fixture)", () => {
  for (const { query, category } of fixture.router) {
    it(`route(${JSON.stringify(query)}) === '${category}'`, () => {
      expect(route(query)).toBe(category);
    });
  }
});

describe("web_search stub parity (tools.py fixture, exercises pyRepr)", () => {
  for (const { query, output } of fixture.web_search) {
    it(`web_search(${JSON.stringify(query)})`, async () => {
      expect(await webSearchTool().func({ query })).toBe(output);
    });
  }
});

describe("string parity", () => {
  it("routing hint matches agent.py construction", () => {
    expect(routingHint(fixture.routing_hint.category)).toBe(fixture.routing_hint.text);
  });

  it("max-iters reply matches anthropic.py:102", () => {
    expect(MAX_ITERS_REPLY).toBe(fixture.max_iters_reply);
  });
});

describe("retrieve_knowledge tool", () => {
  const SNIPS: Snippet[] = [
    { id: "k1", category: "resume", title: "Bullets", content: "Use verbs." },
  ];
  const retriever = {
    retrieve: (_q: string, k: number) => SNIPS.slice(0, k),
  };

  it("formats retrieved snippets (knowledge.py shape)", async () => {
    const out = await retrieveKnowledgeTool(retriever).func({ query: "x" });
    expect(out).toBe("### Bullets (resume)\nUse verbs.");
  });

  it("returns the no-match string when retrieval is empty", async () => {
    const empty = { retrieve: () => [] as Snippet[] };
    const out = await retrieveKnowledgeTool(empty).func({ query: "x" });
    expect(out).toBe("No matching knowledge found.");
  });
});

// --- loop behavior -----------------------------------------------------------

function makeStream(events: AgentStreamEvent[]): AsyncIterable<AgentStreamEvent> {
  return {
    async *[Symbol.asyncIterator]() {
      for (const event of events) {
        yield event;
      }
    },
  };
}

function textIteration(text: string, stop = "end_turn"): AgentStreamEvent[] {
  return [
    { type: "content_block_start", index: 0, content_block: { type: "text" } },
    ...[...text].map((ch) => ({
      type: "content_block_delta",
      delta: { type: "text_delta", text: ch },
    })),
    { type: "content_block_stop", index: 0 },
    { type: "message_delta", delta: { stop_reason: stop } },
  ];
}

function toolIteration(name: string, jsonChunks: string[], preamble = ""): AgentStreamEvent[] {
  const events: AgentStreamEvent[] = [];
  if (preamble) {
    events.push(
      { type: "content_block_start", index: 0, content_block: { type: "text" } },
      { type: "content_block_delta", delta: { type: "text_delta", text: preamble } },
      { type: "content_block_stop", index: 0 },
    );
  }
  events.push(
    {
      type: "content_block_start",
      index: 1,
      content_block: { type: "tool_use", id: "toolu_1", name },
    },
    ...jsonChunks.map((partial) => ({
      type: "content_block_delta",
      delta: { type: "input_json_delta", partial_json: partial },
    })),
    { type: "content_block_stop", index: 1 },
    { type: "message_delta", delta: { stop_reason: "tool_use" } },
  );
  return events;
}

/** Collect everything the loop streams out, decoded back to delta texts. */
function collectorSink(): { sink: SseSink; deltas(): string[] } {
  const chunks: string[] = [];
  const decoder = new TextDecoder();
  return {
    sink: {
      enqueue(chunk: Uint8Array) {
        chunks.push(decoder.decode(chunk));
      },
    },
    deltas: () =>
      chunks
        .join("")
        .split("\n\n")
        .filter((e) => e.startsWith("event: delta"))
        .map((e) => (JSON.parse(e.split("\ndata: ")[1]) as { text: string }).text),
  };
}

function echoTool(name: string, calls: unknown[]): ToolSpec {
  return {
    name,
    description: "test tool",
    input_schema: { type: "object" },
    async func(input) {
      calls.push(input);
      return `result-for:${JSON.stringify(input)}`;
    },
  };
}

describe("runAgentStream", () => {
  it("streams a text-only reply and returns its stop reason", async () => {
    const { sink, deltas } = collectorSink();
    const result = await runAgentStream({
      firstStream: makeStream(textIteration("Hi!")),
      createNext: () => {
        throw new Error("must not be called for a text-only reply");
      },
      message: "hello",
      tools: [],
      sink,
    });
    expect(deltas().join("")).toBe("Hi!");
    expect(result.displayed).toBe("Hi!");
    expect(result.stopReason).toBe("end_turn");
  });

  it("executes a tool then streams the final answer (with separator)", async () => {
    const calls: unknown[] = [];
    const convos: unknown[][] = [];
    const { sink, deltas } = collectorSink();
    const result = await runAgentStream({
      firstStream: makeStream(toolIteration("echo", ['{"que', 'ry": "x"}'], "Checking.")),
      createNext: (convo) => {
        convos.push(JSON.parse(JSON.stringify(convo)) as unknown[]);
        return Promise.resolve(makeStream(textIteration("Answer.")));
      },
      message: "question",
      tools: [echoTool("echo", calls)],
      sink,
    });
    // Tool input assembled from split JSON deltas.
    expect(calls).toEqual([{ query: "x" }]);
    // Preamble streamed, paragraph break, then the final answer.
    expect(result.displayed).toBe("Checking.\n\nAnswer.");
    expect(deltas().join("")).toBe("Checking.\n\nAnswer.");
    expect(result.stopReason).toBe("end_turn");
    // The continuation conversation carries assistant blocks + tool_result.
    expect(convos).toHaveLength(1);
    const convo = convos[0] as Array<{ role: string; content: unknown }>;
    expect(convo[0]).toEqual({ role: "user", content: "question" });
    expect(convo[1].role).toBe("assistant");
    const results = convo[2].content as Array<Record<string, unknown>>;
    expect(convo[2].role).toBe("user");
    expect(results[0].type).toBe("tool_result");
    expect(results[0].tool_use_id).toBe("toolu_1");
    expect(results[0].content).toBe('result-for:{"query":"x"}');
  });

  it("answers Unknown tool for unregistered tool names", async () => {
    const convos: unknown[][] = [];
    const { sink } = collectorSink();
    await runAgentStream({
      firstStream: makeStream(toolIteration("bogus", ["{}"])),
      createNext: (convo) => {
        convos.push(JSON.parse(JSON.stringify(convo)) as unknown[]);
        return Promise.resolve(makeStream(textIteration("ok")));
      },
      message: "q",
      tools: [],
      sink,
    });
    const convo = convos[0] as Array<{ content: unknown }>;
    const results = convo[2].content as Array<Record<string, unknown>>;
    expect(results[0].content).toBe("Unknown tool: bogus");
  });

  it("streams the parity reply when max_iters is exhausted", async () => {
    const calls: unknown[] = [];
    const { sink, deltas } = collectorSink();
    const result = await runAgentStream({
      firstStream: makeStream(toolIteration("echo", ["{}"])),
      createNext: () => Promise.resolve(makeStream(toolIteration("echo", ["{}"]))),
      message: "q",
      tools: [echoTool("echo", calls)],
      sink,
      maxIters: 2,
    });
    expect(calls).toHaveLength(2); // both iterations requested the tool
    expect(deltas().join("")).toBe(MAX_ITERS_REPLY);
    expect(result.displayed).toBe(MAX_ITERS_REPLY);
  });
});
