#!/usr/bin/env python
"""Generate BM25 parity fixtures from the real Python BM25 path.

Runs ``lodestar.retrieval.sparse.BM25Retriever`` (rank-bm25 0.2.2 BM25Okapi) over
``data/knowledge.json`` for a fixed list of representative queries and writes the
ranked snippet ids + scores to ``worker/test/fixtures/bm25_parity.json``.

The TypeScript port (``worker/src/bm25.ts``) is checked against this fixture in
``worker/test/bm25.test.ts`` (ids exact, scores within 1e-9). The fixture's
freshness is checked in ``tests/test_worker_parity.py`` (regenerate in-memory and
compare). Python==fixture and TS==fixture transitively proves Python==TS without a
cross-language runner.

Usage (from the repo root): ``uv run python scripts/gen_bm25_fixtures.py``

Copyright © 2026 Wolfgang Sanyer
Licensed under the Polyform Noncommercial License 1.0.0 (see LICENSE).
"""

from __future__ import annotations

import json
from pathlib import Path

from lodestar.retrieval.knowledge import load_snippets
from lodestar.retrieval.sparse import BM25Retriever, _tokenize

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_PATH = REPO_ROOT / "worker" / "test" / "fixtures" / "bm25_parity.json"

#: Representative queries: the starter-chip questions plus edge cases.
QUERIES: list[str] = [
    # Topical / starter-chip style.
    "How do I find a career fair on campus?",
    "Help me improve my resume with no internships",
    "Where can I find internships as an HBCU student?",
    "How do I network with alumni?",
    "What scholarships are available for HBCU students?",
    "How should I prepare for a behavioral interview?",
    # Single category-token queries.
    "scholarship",
    "interview",
    # Paraphrase / mixed case + punctuation of a topical query.
    "RESUME tips!!! technical skills?",
    # Repeated-term query (per-occurrence accumulation).
    "resume resume resume",
    # Unseen / gibberish words (no vocabulary hit -> empty ranking of positives).
    "zzqqxx flibbertigibbet",
    # Empty-after-tokenize (punctuation only).
    "!!! ??? ...",
]


def build_fixtures() -> dict:
    """Build the fixture dict by ranking each query with the real Python BM25."""
    snippets = load_snippets()
    retriever = BM25Retriever(snippets)
    scores_index = retriever._bm25  # the underlying BM25Okapi

    cases = []
    for query in QUERIES:
        raw_scores = scores_index.get_scores(_tokenize(query))
        ranked = sorted(
            range(len(snippets)),
            key=lambda i: raw_scores[i],
            reverse=True,
        )
        ids = [snippets[i].id for i in ranked]
        # 12 decimal places of precision; the TS test uses 1e-9 tolerance.
        scores = [round(float(raw_scores[i]), 12) for i in ranked]
        cases.append({"query": query, "rankedIds": ids, "scores": scores})

    return {
        "_comment": (
            "Generated by scripts/gen_bm25_fixtures.py from the real Python "
            "rank-bm25 0.2.2 BM25Okapi path over data/knowledge.json. Do not "
            "hand-edit; regenerate after KB or rank-bm25 changes."
        ),
        "params": {"k1": 1.5, "b": 0.75, "epsilon": 0.25},
        "snippetCount": len(snippets),
        "cases": cases,
    }


def main() -> None:
    fixtures = build_fixtures()
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(json.dumps(fixtures, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(fixtures['cases'])} cases to {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
